modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare"

[[mods]]
modId="battlelogscraper"
version="1.6.0"
displayName="Scrapes the battle logs"
displayURL="https://github.com/EnvyWare/"
credits="Envyful"
authors="Envyful"
description='''
Envyful
'''
